### ISSUE TITLE
Catastrophic failure under WSL using LocalAI binaries

### ISSUE THREAD

**Issue by TheSystemGuy1337** [lunamidori5/localai-lunademo#3]
OH NO! A FIRST ISSUE! AND SOMEONE WHO DOESN'T WANT TO FIGHT WITH DOCKER!

The AI was working before, but now for an unknown reason, the AI refuses to work. I keep getting HTTP 500 errors from LAI no matter what I do. Here are the errors in question

`9:19AM ERR error processing message {SystemPrompt:You are a helpful assistant, below is a conversation, please respond with the next message and do not ask follow-up questions Role:System: RoleName:system Content:Rebecca is a helpful Ai that helps the user by using Localai to do what what ever task the user asks them to do.  MessageIndex:0} using template "llama2-7b-chat-gguf-chat": template: prompt:3:5: executing "prompt" at <.Input>: can't evaluate field Input in type model.ChatMessageTemplateData. Skipping!`

`error occurred while running docker-compose up: could not load model: rpc error: code = Unknown desc = failed loading model {"error":{"code":500,"message":"could not load model: rpc error: code = Unknown desc = failed loading model","type":""}} 500 {'error': {'code': 500, 'message': 'could not load model: rpc error: code = Unknown desc = failed loading model', 'type': ''}} {'Date': 'Mon, 13 Nov 2023 15:19:18 GMT', 'Content-Type': 'application/json', 'Content-Length': '120'}
Traceback (most recent call last):
  File "/home/thesystemguy/localai-lunademo/main.py", line 258, in <module>
    textout = str(text_out_unmoded.choices[0].message.content)
NameError: name 'text_out_unmoded' is not defined`

I am on WSL 1, using Ubuntu. Setup was done correctly (just with the Docker setup part gutted)

**Comment by lunamidori5** [comment]
I do know what the bug is and I will fix asap! @TheSystemGuy1337 I oopsed and set it up on master, but master is getting reworked!

**Comment by TheSystemGuy1337** [comment]
I did get it working again by replacing the files; could this be a WSL data corruption bug?

**Comment by lunamidori5** [comment]
Its a I set the localai image to the wrong type bug

**Comment by lunamidori5** [comment]
@TheSystemGuy1337 the docker-composes have been fixed, thank you for pointing that out!
